---
# tasks file for pip_packages
- name: Install global pip packages.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ pip_packages_executable }}"
  with_items: "{{ pip_packages }}"
